name: base
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - cudatoolkit
  - astartes
  - aimsim
  - configargparse
  - lightning>=2.0
  - numpy<2.0
  - pandas
  - rdkit
  - scikit-learn
  - scipy
  - jupyterlab
  - ipykernel
  - ipywidgets
  - tqdm
  - rich
  - matplotlib
  - ray-train
  - ray-tune
  - optuna
  - pip
  - pip:
    - chemprop